---
- name: Recore - Install packages
  apt:
    name:
      - unzip
    state: present

- name: Recore - clone klipper from the master repository
  git:
    repo: https://github.com/Arksine/moonraker
    version: master
    dest: /home/debian/moonraker
    update: yes
    clone: yes
  become: yes
  become_user: debian

- name: Recore - Install moonraker
  shell: |
    /home/debian/moonraker/scripts/install-moonraker.sh
    /home/debian/moonraker/scripts/set-policykit-rules.sh
  sudo: yes
  sudo_user: debian

- name: Recore - copy config
  copy:
    src: moonraker.conf
    dest: /home/debian
    owner: debian
    group: debian

- name: Recore - Create print config folder
  file:
    path: /home/debian/klipper_config
    state: directory
    owner: debian
    group: debian
