---
- name: remove unneeded packages
  apt:
    pkg:
    - smartmontools
    state: absent
    autoremove: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - cpufrequtils
    - pv
    - git
    state: present
    autoremove: yes
    autoclean: yes

- name: Recore - ensure the debian user exists
  user:
    name: debian
    comment: Default user for OctoPrint
    shell: /bin/bash
    groups: tty,dialout
    append: yes
    expires: -1
    home: /home/debian

- name: Recore - make sure the sudoers.d/debian file exists
  file:
    path: /etc/sudoers.d/debian
    owner: root
    group: root
    state: touch

- name: Recore - create folder for klipper logs in /var/log
  file:
    path: /var/log/klipper_logs
    state: directory
    mode: '0755'
    owner: debian
    group: debian

- name: Recore - create folder printer_data in /home/debian
  file:
    path: /home/debian/printer_data
    state: directory
    mode: '0755'
    owner: debian
    group: debian

- name: Recore - create a symlink for the /home/debian/printer_data/logs to store them in /var/log
  file:
    src: /var/log/klipper_logs
    dest: /home/debian/printer_data/logs
    state: link
    owner: debian
    group: debian

- name: enable ssh
  service:
    name: ssh
    enabled: no

- name: Recore - disable root login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*PermitRootLogin.*$'
    replace: '#PermitRootLogin'

- name: get date
  command: 'date --iso-8601'
  register: build_date

- name: Register ReFactor version
  script:
    cmd: '{{ role_path }}/files/get_refactor_version.sh'
  register: version

- name: write dogtag
  copy:
    dest: '/etc/{{ dogtag }}'
    content: '{{ version.stdout }} {{ build_date.stdout }}'

- name: set hostname
  copy:
    dest: /etc/hostname
    content: "{{ platform }}\n"

- name: set root password
  user:
    name: root
    password: "{{ 'kamikaze' | password_hash('sha512') }}"

- name: set debian password
  user:
    name: debian
    password: "{{ 'temppwd' | password_hash('sha512') }}"

- name: write issue and issue.net
  copy:
    dest: '{{ item }}'
    content: |
      {{ version.stdout }}

      Check that nothing is printing before any intensive operation!
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: Recore - fix home ownership
  command: chown -R debian:debian /home/debian

- name: Recore - Add ttyGS0 to /etc/securetty
  lineinfile:
    path: /etc/securetty
    line: ttyGS0
    state: present

- name: Recore - Enable ttyGS0 getty service
  service:
    name: serial-getty@ttyGS0.service
    enabled: yes

- name: Recore - force debian password reset
  shell: chage -d 0 debian

- name: Recore - install script to set CPU to use performance governor
  copy:
    src: '{{ role_path }}/files/cpufreq.sh'
    dest: /opt/cpufreq.sh
    mode: '0755'
    owner: debian
    group: debian

- name: Recore - install service for CPU performance governor use
  copy:
    src: '{{ role_path }}/files/cpufreq.service'
    dest: /etc/systemd/system/cpufreq.service
    mode: '0644'
    owner: root
    group: root

- name: Recore - enable the CPU performance governor usage
  systemd:
    daemon-reload: true
    enabled: true
    name: cpufreq

- name: Recore - add support for system upgrade
  copy:
    src: 100update
    dest: /etc/apt/apt.conf.d/100update
    mode: '0644'
