name: Build Refactor on AWS
on: push
jobs:
  build-recore:
    runs-on: ubuntu-latest
    steps:
      - name: Build Refactor Recore on AWS
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd Refactor
            git fetch
            export branch=$(echo ${{github.ref}} |  cut -d'/' -f 3-)
            git checkout $branch
            git pull
            git log HEAD --oneline --no-walk
            rm -rf Refactor-*.xz
            sudo ./build-image-in-chroot-end-to-end.sh recore
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true

  build-replicape:
    runs-on: ubuntu-latest
    steps:
      - name: Build Refactor Replicape on AWS
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd Refactor
            git fetch
            export branch=$(echo ${{github.ref}} |  cut -d'/' -f 3-)
            git checkout $branch
            git pull
            git log HEAD --oneline --no-walk
            rm -rf Refactor-*.xz
            sudo ./build-image-in-chroot-end-to-end.sh replicape
          host: ${{ secrets.HOST_REPLICAPE }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
